### ISSUE TITLE
Discuss change in game engine

### ISSUE THREAD

**Issue by BunchesOfLife** [rit-sse/render-ai#12]
Brian and I have come to an agreement that the current Isogenic  Engine is not a good idea to use.  Its documentation is outdated, it's not open source, requires a license, and the example code it gives is buggy and doesn't work.  Phaser is a much more widely used open source engine that also uses Node.js, and many forums and ratings agree that Phaser is better.  Since we have not started actual coding yet, now is the time to decide on this.

**Comment by BunchesOfLife** [comment]
Update:  from more research, it seems Phaser is better built for mobile browser development whereas the isogenic engine has easier multiplayer setup.  This sways back toward using the isogenic engine, but i think it should probably still be discussed in person.  we need a meeting Dom.

**Comment by bjpicciano** [comment]
We discussed changing from the isogenic engine but decided to stick with it. Our main issue, deployment, has been figured out. The only remaining issue is the lack of documentation.
