### ISSUE TITLE
Boss Attributes

### ISSUE THREAD

**Issue by lance13c** [rit-sse/render-ai#7]

**Comment by lance13c** [comment]
What are the boss attributes. Giving a fixed amount of energy usage, energy regen.  What can the boss do?

**Comment by BunchesOfLife** [comment]
Tentative plan for boss:  Boss consists of a core surrounded by a mass of destroyable triangles.  Players can destroy the triangles to whittle down the mass to reveal the core.  Destroying the core defeats the boss.  The boss can spawn minions to fight the players as well as shields to block players' attacks.  If any particular section of the external mass gets weakened, the boss can focus defenses on that area.  Boss regenerates triangles it has lost.

**Comment by BunchesOfLife** [comment]
Tentative plan for boss:  Boss consists of a core surrounded by a mass of destroyable triangles.  Players can destroy the triangles to whittle down the mass to reveal the core.  Destroying the core defeats the boss.  The boss can spawn minions to fight the players as well as shields to block players' attacks.  If any particular section of the external mass gets weakened, the boss can focus defenses on that area.  Boss regenerates triangles it has lost.

**Comment by BunchesOfLife** [comment]
Tentative plan for boss:  Boss consists of a core surrounded by a mass of destroyable triangles.  Players can destroy the triangles to whittle down the mass to reveal the core.  Destroying the core defeats the boss.  The boss can spawn minions to fight the players as well as shields to block players' attacks.  If any particular section of the external mass gets weakened, the boss can focus defenses on that area.  Boss regenerates triangles it has lost.

**Comment by BunchesOfLife** [comment]
Tentative plan for boss:  Boss consists of a core surrounded by a mass of destroyable triangles.  Players can destroy the triangles to whittle down the mass to reveal the core.  Destroying the core defeats the boss.  The boss can spawn minions to fight the players as well as shields to block players' attacks.  If any particular section of the external mass gets weakened, the boss can focus defenses on that area.  Boss regenerates triangles it has lost.

**Comment by BunchesOfLife** [comment]
Tentative plan for boss:  Boss consists of a core surrounded by a mass of destroyable triangles.  Players can destroy the triangles to whittle down the mass to reveal the core.  Destroying the core defeats the boss.  The boss can spawn minions to fight the players as well as shields to block players' attacks.  If any particular section of the external mass gets weakened, the boss can focus defenses on that area.  Boss regenerates triangles it has lost.

**Comment by BunchesOfLife** [comment]
Tentative plan for boss:  Boss consists of a core surrounded by a mass of destroyable triangles.  Players can destroy the triangles to whittle down the mass to reveal the core.  Destroying the core defeats the boss.  The boss can spawn minions to fight the players as well as shields to block players' attacks.  If any particular section of the external mass gets weakened, the boss can focus defenses on that area.  Boss regenerates triangles it has lost.

**Comment by BunchesOfLife** [comment]
Tentative plan for boss:  Boss consists of a core surrounded by a mass of destroyable triangles.  Players can destroy the triangles to whittle down the mass to reveal the core.  Destroying the core defeats the boss.  The boss can spawn minions to fight the players as well as shields to block players' attacks.  If any particular section of the external mass gets weakened, the boss can focus defenses on that area.  Boss regenerates triangles it has lost.

**Comment by BunchesOfLife** [comment]
Tentative plan for boss:  Boss consists of a core surrounded by a mass of destroyable triangles.  Players can destroy the triangles to whittle down the mass to reveal the core.  Destroying the core defeats the boss.  The boss can spawn minions to fight the players as well as shields to block players' attacks.  If any particular section of the external mass gets weakened, the boss can focus defenses on that area.  Boss regenerates triangles it has lost.

**Comment by BunchesOfLife** [comment]
Tentative plan for boss:  Boss consists of a core surrounded by a mass of destroyable triangles.  Players can destroy the triangles to whittle down the mass to reveal the core.  Destroying the core defeats the boss.  The boss can spawn minions to fight the players as well as shields to block players' attacks.  If any particular section of the external mass gets weakened, the boss can focus defenses on that area.  Boss regenerates triangles it has lost.

**Comment by BunchesOfLife** [comment]
Tentative plan for boss:  Boss consists of a core surrounded by a mass of destroyable triangles.  Players can destroy the triangles to whittle down the mass to reveal the core.  Destroying the core defeats the boss.  The boss can spawn minions to fight the players as well as shields to block players' attacks.  If any particular section of the external mass gets weakened, the boss can focus defenses on that area.  Boss regenerates triangles it has lost.

**Comment by BunchesOfLife** [comment]
Tentative plan for boss:  Boss consists of a core surrounded by a mass of destroyable triangles.  Players can destroy the triangles to whittle down the mass to reveal the core.  Destroying the core defeats the boss.  The boss can spawn minions to fight the players as well as shields to block players' attacks.  If any particular section of the external mass gets weakened, the boss can focus defenses on that area.  Boss regenerates triangles it has lost.

**Comment by BunchesOfLife** [comment]
As a note, I suggest that the triangles that the boss's mass is made of should be very small isosceles  triangles for ease of auto-construction.
